// <auto-generated />
using System;
using DefendX.API.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DefendX.API.Migrations.LogData
{
    [DbContext(typeof(LogDataContext))]
    [Migration("20190212071024_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DefendX.API.Domain.AggregatesModel.LogAggregate.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("EntityId");

                    b.Property<string>("IpAddress");

                    b.Property<int>("LogEntryTypeId");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Stack");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LogEntryTypeId");

                    b.ToTable("LogEntry");
                });

            modelBuilder.Entity("DefendX.API.Domain.AggregatesModel.LogAggregate.LogEntryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("LogEntryType");
                });

            modelBuilder.Entity("DefendX.API.Domain.AggregatesModel.LogAggregate.LogEntry", b =>
                {
                    b.HasOne("DefendX.API.Domain.AggregatesModel.LogAggregate.LogEntryType", "LogEntryType")
                        .WithMany("LogEntries")
                        .HasForeignKey("LogEntryTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
